name = "musoudle"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "CHARACTERS_KV", id = "de828a108ec7481599121a7c1fe4ad46" },
  { binding = "USER_GUESSES_KV", id = "e4130fe1b5394af7b9a0e26266ee898e" },
]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[env.prod]
name = "musoudle"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
kv_namespaces = [
  { binding = "CHARACTERS_KV", id = "de828a108ec7481599121a7c1fe4ad46" },
  { binding = "USER_GUESSES_KV", id = "e4130fe1b5394af7b9a0e26266ee898e" }
]
routes = [
  { pattern = "musoudle.net", custom_domain = true }
]
services = [
  { binding = "DURABLE_MUSOUDLE_COUNTER", service = "durable-musoudle-counter"}
]
[env.prod.vars]
MUSOUDLE_COUNTER_WS = "https://durable-musoudle-counter.kamito14321.workers.dev"

[env.staging]
name = "musoudle-staging"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
kv_namespaces = [
  { binding = "CHARACTERS_KV", id = "95416ded0b3945c3ac45d7811130dad8" },
  { binding = "USER_GUESSES_KV", id = "700ae3d6e5194b4c8dd133947c26efc2" }
]
services = [
  { binding = "DURABLE_MUSOUDLE_COUNTER", service = "durable-musoudle-counter-staging" }
]
[env.staging.vars]
MUSOUDLE_COUNTER_WS = "https://durable-musoudle-counter-staging.kamito14321.workers.dev"